<!-- sidebar.inc -->
<aside class="sidebar">
  <section>
    <h1><a href="/docs/manpages.html">Manpages</a></h1>
    <ul>
      <li><a href="/docs/manmaster">Master</a></li>
      <li><a href="/docs/man1.0.2">1.0.2</a></li>
      <li><a href="/docs/man1.0.1">1.0.1</a></li>
      <li><a href="/docs/man1.0.0">1.0.0</a></li>
      <li><a href="/docs/man0.9.8">0.9.8</a></li>
    </ul>
  </section>
</aside>
<!-- end -->
