
<ul type=square>
<define-tag mirror>
<preserve url>
<preserve loc>
<set-var %attributes>
<li><a href="<get-var url>"><get-var url></a>
    &nbsp;&nbsp;[<get-var loc>]
<restore loc>
<restore url>
</define-tag>

<mirror url="ftp://ftp.openssl.org/source/" loc="CH"> 
<mirror url="ftp://sunsite.cnlab-switch.ch/mirror/openssl/" loc="CH">
<mirror url="ftp://ftp.pca.dfn.de/pub/tools/net/openssl/" loc="DE">
<mirror url="ftp://ftp.ecrc.net/pub/security/openssl/" loc="DE">
<mirror url="ftp://ftp.uni-trier.de/pub/unix/security/openssl/" loc="DE">
<mirror url="ftp://opensores.thebunker.net/pub/mirrors/openssl/" loc="UK">
<mirror url="ftp://ftp.net.lut.ac.uk/openssl/" loc="UK">
<mirror url="ftp://ftp.sunet.se/pub/security/tools/net/openssl/" loc="SE">
<mirror url="ftp://ftp.psy.uq.edu.au/pub/Crypto/" loc="AU">

</ul>

