
<ul type=square>
<define-tag mirror>
<preserve url>
<preserve loc>
<set-var %attributes>
<li><a href="<get-var url>" rel="nofollow"><get-var url></a>
    &nbsp;&nbsp;[<get-var loc>]
<restore loc>
<restore url>
</define-tag>

<mirror url="ftp://ftp.openssl.org/source/" loc="CH"> 
<mirror url="ftp://sunsite.cnlab-switch.ch/mirror/openssl/" loc="CH">
<mirror url="ftp://ftp.funet.fi/pub/crypt/cryptography/libs/openssl/" loc="FI">
<mirror url="ftp://ftp.pca.dfn.de/pub/tools/net/openssl/" loc="DE">
<mirror url="ftp://ftp.webmonster.de/pub/openssl/" loc="DE">
<mirror url="ftp://sunsite.uio.no/pub/security/openssl/" loc="NO">
<mirror url="ftp://ftp.sunet.se/pub/security/tools/net/openssl/" loc="SE">
<mirror url="ftp://ftp.chl.chalmers.se/pub/unix/security/openssl/" loc="SE">
<mirror url="ftp://ftp.psy.uq.edu.au/pub/Crypto/" loc="AU">
<mirror url="ftp://mirror.aarnet.edu.au/pub/openssl/" loc="AU">
<mirror url="ftp://gd.tuwien.ac.at/infosys/security/openssl/" loc="AT">
<mirror url="ftp://ftp.av8.com/pub/mirrors/openssl/" loc="US">
<mirror url="ftp://ftp.styx.net/mirrors/crypto/openssl/" loc="US">
<mirror url="ftp://ftp.kfki.hu/pub/packages/security/openssl/" loc="HU">
<mirror url="ftp://guest.kuria.katowice.pl/pub/openssl/" loc="PL">
<mirror url="ftp://ftp.win.ne.jp/pub/network/security/openssl/" loc="JP">
<mirror url="ftp://ftp.infoscience.co.jp/pub/Crypto/SSL/openssl/" loc="JP">
<mirror url="ftp://ftp.ncu.edu.tw/Unix/Crypto/OpenSSL/" loc="TW">
<mirror url="ftp://ftp.mit.com.tw/pub/SSL/openssl/" loc="TW">
<mirror url="ftp://ftp.elab.co.za/support/openssl/source/" loc="ZA">
<mirror url="ftp://ftp.fisek.com.tr/pub/openssl/" loc="TR">
<mirror url="ftp://ftp.fi.muni.cz/pub/openssl/" loc="CZ">
<mirror url="ftp://ftp.sunsite.utk.edu/pub/openssl/" loc="US">
<mirror url="ftp://ftp.linux.hr/pub/openssl/" loc="HR">
<mirror url="ftp://ftp.1stnet.co.uk/pub/mirrors/openssl/" loc="UK">
<mirror url="ftp://mirror.aarnet.edu.au/pub/openssl/" loc="AU">
<mirror url="ftp://storm.alert.sk/mirrors/openssl/" loc="SK">
<mirror url="ftp://ftp.grmbl.com/pub/openssl/" loc="BE">
<mirror url="ftp://ftp.gin.cz/pub/MIRRORS/ftp.openssl.org/" loc="CZ">
<mirror url="ftp://ftp.calyx.nl/pub/openssl/" loc="NL">
<mirror url="ftp://ftp.duth.gr/pub/OpenSSL/" loc="GR">
<mirror url="ftp://ftp.linux.gr/pub/crypto/openssl/" loc="GR">
<mirror url="ftp://ftp.hjc.edu.sg/opensource/openssl/" loc="SG">
<mirror url="ftp://ftp.singnet.com.sg/opensource/openssl/" loc="SG">
<mirror url="ftp://mirrors.usc.edu/pub/openssl/" loc="US">
<mirror url="rsync://mirrors.usc.edu/openssl/" loc="US">
<mirror url="http://openssl.linux-mirror.org/" loc="DE">
<mirror url="http://openssl.oss-mirror.org/" loc="IE">
<mirror url="http://openssl.onionland.org/" loc="DE">
<mirror url="rsync://onionland.org/openssl/" loc="DE">
<mirror url="http://www.securehost.com/mirror/openssl/" loc="BS">
<mirror url="http://www.very-clever.com/download/openssl/" loc="DE">
<mirror url="http://openssl.parentinginformed.com/" loc="CA">
<mirror url="http://openssl.promotionalpro.com/" loc="BY">
<mirror url="http://mirror.vocabbuilder.net/openssl/" loc="IN">
<mirror url="http://openssl.initrd.net/" loc="DE">
<mirror url="ftp://ftp.tpnet.pl/pub/security/openssl/" loc="PL">
<mirror url="rsync://ftp.tpnet.pl/pub/security/openssl/" loc="PL">
<mirror url="http://openssl.skazkaforyou.com/" loc="CA">
<mirror url="http://openssl.raffsoftware.com/" loc="CA">

</ul>

