
<ul type=square>
<define-tag mirror>
<preserve url>
<preserve loc>
<set-var %attributes>
<li><a href="<get-var url>"><get-var url></a>
    &nbsp;&nbsp;[<get-var loc>]
<restore loc>
<restore url>
</define-tag>

<mirror url="ftp://ftp.openssl.org/source/" loc="CH"> 
<mirror url="ftp://sunsite.cnlab-switch.ch/mirror/openssl/" loc="CH">
<mirror url="ftp://ftp.pca.dfn.de/pub/tools/net/openssl/" loc="DE">
<mirror url="ftp://ftp.ecrc.net/pub/security/openssl/" loc="DE">
<mirror url="ftp://ftp.uni-trier.de/pub/unix/security/openssl/" loc="DE">
<mirror url="ftp://opensores.thebunker.net/pub/mirrors/openssl/" loc="UK">
<mirror url="ftp://ftp.net.lut.ac.uk/openssl/" loc="UK">
<mirror url="ftp://sunsite.uio.no/pub/security/openssl/" loc="NO">
<mirror url="ftp://ftp.sunet.se/pub/security/tools/net/openssl/" loc="SE">
<mirror url="ftp://ftp.psy.uq.edu.au/pub/Crypto/" loc="AU">
<mirror url="ftp://gd.tuwien.ac.at/infosys/security/openssl/" loc="AT">
<mirror url="ftp://glock.missouri.edu/pub/openssl/" loc="US">
<mirror url="ftp://ftp.av8.com/pub/mirrors/openssl/" loc="US">
<mirror url="ftp://ftp.styx.net/mirrors/crypto/openssl/" loc="US">
<mirror url="ftp://gw.inetlab.com/mirrors/openssl/" loc="RU">
<mirror url="ftp://ftp.ebizlab.hit.bme.hu/pub/openssl/" loc="HU">
<mirror url="ftp://guest.kuria.katowice.pl/pub/openssl/" loc="PL">
<mirror url="ftp://ftp.win.ne.jp/pub/network/security/openssl/" loc="JP">
<mirror url="ftp://ftp.infoscience.co.jp/pub/Crypto/SSL/openssl/" loc="JP">
<mirror url="ftp://ftp.ncu.edu.tw/Unix/Crypto/OpenSSL/" loc="TW">
<mirror url="ftp://ftp.mit.com.tw/pub/SSL/openssl/" loc="TW">
<mirror url="ftp://ftp.elab.co.za/support/openssl/source/" loc="ZA">

</ul>

