<!-- sidebar.inc -->
<!-- This needs full paths since the subdirs include this navbar. -->
<aside class="sidebar">
  <section>
    <h1><a href="/source">Downloads</a></h1>
    <ul>
      <li>
	<a href="/source/gitrepo.html">Git Repository</a>
      </li>
      <li>
	<a href="/source/license.html">License</a>
      </li>
      <li>
        <a href="/source/old">Old Releases</a>
      </li>
      <li>
	<a href="mirror.html">Mirror Sites</a>
      </li>
    </ul>
  </section>
</aside>
<!-- end -->
