# This is a basic workflow that is manually triggered

name: Manual Doc build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build_doc_site:
    # The type of runner that the job will run on
    runs-on: [ doc-builder-22.04 ]
#    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Build_web
        run: /scripts/build_doc.sh
