###
name: Automatic web build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
jobs:
  # This workflow contains a single job called "greet"
  build_web_site:
    # The type of runner that the job will run on
    runs-on: [ web-builder-22.04 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Build_web
        run: /scripts/build_web.sh
      

